return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cpp",
        "fidl",
        "fish",
        "git_rebase",
        "gitcommit",
        "gn",
        "go",
        "gomod",
        "gosum",
        "html",
        "javascript",
        "json",
        "json5",
        "kdl",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "rust",
        "toml",
        "typescript",
        "yaml",
      },
    },
  },
}
